<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Np n ng Tuyn</name>
   <tag></tag>
   <elementGuidId>04f62c74-54c3-4bf3-a250-cae5c0954f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']/section/div[7]/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7ecabf4-83a5-41c0-acca-a684f8b75a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>ae9abec2-a367-46ae-b7f7-313771d4c887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-gradient btnApplyClick</value>
      <webElementGuid>8ca4ecb2-56b2-42b3-991e-7c039771cc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Nộp Đơn Ứng Tuyển </value>
      <webElementGuid>5e157aec-7b77-4067-b835-9b2df3d31d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/section[@class=&quot;job-detail-content&quot;]/div[@class=&quot;job-detail-bottom sticky&quot;]/div[@class=&quot;job-detail-bottom-wrapper&quot;]/div[@class=&quot;apply-now-content&quot;]/div[@class=&quot;apply-now-right&quot;]/div[@class=&quot;apply-now-btn&quot;]/a[@class=&quot;btn-gradient btnApplyClick&quot;]</value>
      <webElementGuid>d3a7d976-5d04-4389-94b7-b4291feb17eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/section/div[7]/div/div/div[2]/div/a</value>
      <webElementGuid>34d9b8c4-5b7b-4c5a-9ac3-64420635591d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Nộp Đơn Ứng Tuyển')])[2]</value>
      <webElementGuid>b2e9fc6e-6450-4efd-9104-16ff94f7bfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Báo xấu'])[4]/following::a[1]</value>
      <webElementGuid>3b193914-9ab6-42cb-9c66-d57787f2cb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thử mã mới'])[1]/following::a[1]</value>
      <webElementGuid>f505a62a-be0d-427f-859b-000d8fb3e771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dành Cho Ứng Viên'])[1]/preceding::a[3]</value>
      <webElementGuid>63e5553b-0d66-421f-87ee-32c3be84b18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Việc làm mới nhất'])[2]/preceding::a[3]</value>
      <webElementGuid>04fd2379-fa1c-4602-abe4-c089388be08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>34fc917c-2910-44d7-b5c7-0e22630d04da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/a</value>
      <webElementGuid>d8336795-6c11-4d68-b108-a9516ec6d66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = ' Nộp Đơn Ứng Tuyển ' or . = ' Nộp Đơn Ứng Tuyển ')]</value>
      <webElementGuid>6fac4cb2-2888-40f4-9262-0472cde2e729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
