<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Chn t my tnh_mdi mdi-folder-outline</name>
   <tag></tag>
   <elementGuidId>f0b5d164-8168-4111-8175-144ee97f568f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmApplyjob']/div[4]/div[2]/div/div/div/label/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.mdi.mdi-folder-outline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>b20693a9-fdd4-49b3-b1ee-67741498ee7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-folder-outline</value>
      <webElementGuid>de208b28-3c16-4a3c-939d-3954b7515dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmApplyjob&quot;)/div[@class=&quot;upload-resume&quot;]/div[@class=&quot;form-group form-radio&quot;]/div[@class=&quot;list-radio&quot;]/div[@class=&quot;list-choose&quot;]/div[@class=&quot;choose-mycomputer&quot;]/label[1]/em[@class=&quot;mdi mdi-folder-outline&quot;]</value>
      <webElementGuid>f09bedb3-cd05-4cb0-9557-a77d93805591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/div/div/div/label/em</value>
      <webElementGuid>a0e54f82-fd97-44d6-8def-4293c5ea0bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/em</value>
      <webElementGuid>f7ab8a3a-e826-494c-bc4a-a311870a32fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
