<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload h s H tr nh dng .doc, .docx, ._60c131</name>
   <tag></tag>
   <elementGuidId>388cb41e-24d7-4c45-893c-c6873c40b5fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8c64e3bd-13e6-44fd-bf8c-6b653cb3d62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>upload-resume</value>
      <webElementGuid>fb332fb6-c341-4b0f-9225-f7bce41f1e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB</value>
      <webElementGuid>0ab260eb-08df-46f9-9dab-9d750248d2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmApplyjob&quot;)/div[@class=&quot;upload-resume&quot;]/div[@class=&quot;form-group form-radio&quot;]/label[1]</value>
      <webElementGuid>e8fb6d2a-1cd5-4358-af08-54b2400dae73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      <webElementGuid>92aa6fce-938e-420c-8e25-a4cc9296cbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo hồ sơ mới!'])[1]/following::label[1]</value>
      <webElementGuid>93ad74ae-ea2a-44a8-a821-75aacbc29f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn từ hồ sơ của bạn'])[1]/following::label[1]</value>
      <webElementGuid>a4dc0a0a-d5e2-415b-b925-ab6fdbedd2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn từ máy tính'])[1]/preceding::label[1]</value>
      <webElementGuid>d7b32207-b41e-435e-83a7-f8b00e5090cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn file từ Dropbox'])[1]/preceding::label[2]</value>
      <webElementGuid>c91f8368-5796-48c5-af42-04abad2e8471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB']/parent::*</value>
      <webElementGuid>2bd5580b-ca31-4464-87ca-92097642ce4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label</value>
      <webElementGuid>36bc8758-6034-486f-a9e3-ccbdc776a1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB' or . = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB')]</value>
      <webElementGuid>6aaa5abd-c8b0-4f4c-a50c-0ab5a05e5d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
