<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Np ng Tuyn</name>
   <tag></tag>
   <elementGuidId>dd52b84e-893c-4c95-a38a-929e76429d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnsubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b12dc177-0967-4074-adcd-77b4bef7b294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-gradient</value>
      <webElementGuid>65f8f9ab-b8fe-4ed0-9829-b66b06334490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>70e9d3b1-a22f-4254-8bdb-fc44e3c68e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsubmit</value>
      <webElementGuid>642127e4-2fb7-45ce-a4c6-5979cf76bcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dfc2c2be-4554-4578-af5f-cd3b4f9c55c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nộp Ứng Tuyển</value>
      <webElementGuid>0e2e9107-e632-4e75-8dce-9657c789c650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsubmit&quot;)</value>
      <webElementGuid>d757980d-c3d4-46bc-b598-4dee67d2df53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsubmit']</value>
      <webElementGuid>96347f4b-296c-48b5-a9f6-478c44e4b0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[5]/button</value>
      <webElementGuid>ea93a4e8-51a3-4756-a006-989d72587064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tiếng Anh'])[1]/following::button[1]</value>
      <webElementGuid>a562c357-accd-416f-836a-6c768d5b5016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thông tin việc làm'])[1]/preceding::button[1]</value>
      <webElementGuid>ef3ebcf7-57f3-477d-b84c-f115da9dbc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vị trí / Chức danh:'])[1]/preceding::button[1]</value>
      <webElementGuid>05971acf-f1e9-4cdd-90cb-94dc92b285ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nộp Ứng Tuyển']/parent::*</value>
      <webElementGuid>671f2f17-5e19-416b-959e-c421750939b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button</value>
      <webElementGuid>fc38c4e1-0593-4364-b6a4-e62d55cd53b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'btnsubmit' and @id = 'btnsubmit' and @type = 'submit' and (text() = 'Nộp Ứng Tuyển' or . = 'Nộp Ứng Tuyển')]</value>
      <webElementGuid>421f3268-a883-442c-91a0-b33edc90f483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
