<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_picture_as_pdf_uploadFile</name>
   <tag></tag>
   <elementGuidId>60a19e55-ea5f-4d61-87f7-2f86d7117c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadFile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>379e629e-3bd3-4c8e-b21d-ae79498842a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f8e15df-a7c6-41eb-a231-111fc65789a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadFile</value>
      <webElementGuid>cc6f5696-4d6e-4e6f-92b1-7a0c64eae12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valid</value>
      <webElementGuid>c9c4043d-2b18-4e01-8961-81f1ff7d516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadFile&quot;)</value>
      <webElementGuid>ed3e7970-f3ad-4b76-a025-50a95bbd6316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadFile']</value>
      <webElementGuid>88de6a44-f528-4b99-91aa-554921f7e783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>c72fa413-487a-4848-bd76-6f02493dd4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/input</value>
      <webElementGuid>0500c69c-e911-46eb-af20-2cdc04b8cd6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uploadFile']</value>
      <webElementGuid>f9966274-1f5c-4f8a-8948-8980234bea40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
