<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_picture_as_pdf_uploadFile</name>
   <tag></tag>
   <elementGuidId>a22f9e76-cffa-4235-a340-5ec4ba407d46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadFile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;attach_file&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>992df39d-c0f2-407a-8745-565c1fd2753a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e79984b-48fe-45e1-bb9c-1d264cc230c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadFile</value>
      <webElementGuid>ac41370a-cf54-417e-8cd5-3a56dd4b60ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadFile&quot;)</value>
      <webElementGuid>9e2bfab2-31d1-4f46-9fde-891bde3b9ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadFile']</value>
      <webElementGuid>059fa909-61e3-4f28-a02e-b66cf216f3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>65aeb778-6485-4f0c-9592-f0c8e7885131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>946575e9-285e-40c7-975f-f1d41d742905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uploadFile']</value>
      <webElementGuid>7df9e638-6375-4c13-8015-ea36856b7723</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
