<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload h s H tr nh dng .doc, .docx, ._60c131</name>
   <tag></tag>
   <elementGuidId>d97c24aa-b832-413b-af4c-d7bee18b47e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>46eca7b6-9133-4e61-b404-e90b40475224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>upload-resume</value>
      <webElementGuid>a6baf114-27bd-44a9-939d-4444a66058fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB</value>
      <webElementGuid>538aa056-ad8e-4676-af60-416588d5cf92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmApplyjob&quot;)/div[@class=&quot;upload-resume&quot;]/div[@class=&quot;form-group form-radio&quot;]/label[1]</value>
      <webElementGuid>4a8fb908-6ffc-4301-ba8c-7b9fec276c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      <webElementGuid>9bc4e0ae-1bc7-4c1c-a60d-726156171466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo hồ sơ mới!'])[1]/following::label[1]</value>
      <webElementGuid>7f9c194b-83cd-48d8-b020-ec78cd58fe12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Xem]'])[2]/following::label[1]</value>
      <webElementGuid>e0b6ddc9-8468-46ed-8de7-4412e5b97f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn từ máy tính'])[1]/preceding::label[1]</value>
      <webElementGuid>98361d1a-b7d4-4900-b74f-d478f9a5a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn file từ Dropbox'])[1]/preceding::label[2]</value>
      <webElementGuid>63e4e1a9-aec8-41b8-9488-016e2d9b6fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB']/parent::*</value>
      <webElementGuid>0aa0e95d-ad24-467c-999c-cba4521fb696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label</value>
      <webElementGuid>947c4781-03fd-4d66-9aa2-2e34159143c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB' or . = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB')]</value>
      <webElementGuid>0c222e12-141f-4b5d-b823-42b41459f6d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
