<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload h s H tr nh dng .doc, .docx, ._60c131</name>
   <tag></tag>
   <elementGuidId>f52a8bdd-f2e0-4b93-87b2-2ffde41bde50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3be73b27-a638-4e3c-94ce-12a0bfaa952e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>upload-resume</value>
      <webElementGuid>cec91883-522f-4a80-bd49-56e2924527a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB</value>
      <webElementGuid>288507eb-95be-4653-8015-1aaaa427e281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmApplyjob&quot;)/div[@class=&quot;upload-resume&quot;]/div[@class=&quot;form-group form-radio&quot;]/label[1]</value>
      <webElementGuid>43bd5058-2cca-450c-a953-d5088075e4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmApplyjob']/div[4]/div[2]/label</value>
      <webElementGuid>901bd2c7-a7c9-4cf1-b530-2629606af363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo hồ sơ mới!'])[1]/following::label[1]</value>
      <webElementGuid>94372a86-05b1-4c0d-b05d-996be72f1f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn từ hồ sơ của bạn'])[1]/following::label[1]</value>
      <webElementGuid>a7851e1d-aaa5-4e6a-bac8-2db732bab99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn từ máy tính'])[1]/preceding::label[1]</value>
      <webElementGuid>1ab063ad-e833-408b-81ee-e089150670e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chọn file từ Dropbox'])[1]/preceding::label[2]</value>
      <webElementGuid>a2251d4b-703a-4419-baff-9af09e6ee2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB']/parent::*</value>
      <webElementGuid>fed00c78-66e5-46b3-97da-16e044bc2185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/label</value>
      <webElementGuid>ae54443e-a161-47bc-866a-a802f60b3624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB' or . = 'Upload hồ sơ: Hỗ trợ định dạng *.doc, *.docx, *.pdf và không quá 3MB')]</value>
      <webElementGuid>6c63cf40-1da8-46cf-b115-def94eb6aa3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
