<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng</name>
   <tag></tag>
   <elementGuidId>65deab99-c379-41f3-b6d9-e8fad6f25bcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn-close-modal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fancybox-container-1']/div[2]/div[4]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>004d0363-cc10-4cb2-bfc0-dfb4b52fe97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-close-modal</value>
      <webElementGuid>5150ff34-6d1f-420c-861b-ba42dc86eccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>dfeb3c1e-454a-4c78-aba3-3578a2cd2d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đóng</value>
      <webElementGuid>93b8fcd7-d76c-4411-ae58-01fc70d85a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-container-1&quot;)/div[@class=&quot;fancybox-inner&quot;]/div[@class=&quot;fancybox-stage&quot;]/div[@class=&quot;fancybox-slide fancybox-slide--html fancybox-slide--current fancybox-slide--complete&quot;]/div[@class=&quot;remove-modal fancybox-content&quot;]/div[@class=&quot;modal-body&quot;]/a[@class=&quot;btn-close-modal&quot;]</value>
      <webElementGuid>1b0a684a-6fa9-4028-b66d-6e1cec045b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-container-1']/div[2]/div[4]/div/div/div[2]/a</value>
      <webElementGuid>c92d52c3-203e-4fc3-bde7-3308a3ecd65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đóng')]</value>
      <webElementGuid>c2386379-5fa9-4bc0-8b8a-0752fb4a7664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::a[1]</value>
      <webElementGuid>4f7b3190-9840-49d7-a53d-3aab6a90da56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đóng']/parent::*</value>
      <webElementGuid>827f090a-0bc7-43ee-96a5-8dca3be11d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>3899c5dd-0232-42a4-9a44-3c056c4bbad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/a</value>
      <webElementGuid>d43b0dde-23c0-4662-baa6-82adf7b21686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Đóng' or . = 'Đóng')]</value>
      <webElementGuid>8c832d3c-89c2-4d5a-9428-5a5962bfb950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
