<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test1                                    _8a783d</name>
   <tag></tag>
   <elementGuidId>acbd21c4-ae97-4a61-af64-70772aa9ed2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='job-item-35B9CDA9']/div/div[2]/div/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.job_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba4db6be-4b7d-4eab-a80d-05e7621866aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job_link</value>
      <webElementGuid>95698719-d65a-489f-a22f-e9c6c0c5b530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>35B9CDA9</value>
      <webElementGuid>9e735935-7723-498d-ab30-05e011c3312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9CDA9.html</value>
      <webElementGuid>0886959c-8790-4c3d-ba9b-84f29e710b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>90805e45-c656-4ec2-b44f-3b1ee917cbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test1</value>
      <webElementGuid>d20b69d7-1cc6-45e4-8d36-81d5a86bf00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Test1
                                         (Mới)                                     </value>
      <webElementGuid>0be18ebf-061b-40fe-bb9e-fe1762d4bd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-item-35B9CDA9&quot;)/div[@class=&quot;figure&quot;]/div[@class=&quot;figcaption&quot;]/div[@class=&quot;title&quot;]/h2[1]/a[@class=&quot;job_link&quot;]</value>
      <webElementGuid>b2631ed2-3f14-4f4f-88ea-d39571f168e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-item-35B9CDA9']/div/div[2]/div/h2/a</value>
      <webElementGuid>581c70c1-046d-4079-ba84-1b894493b18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mức lương'])[2]/following::a[2]</value>
      <webElementGuid>c97989b8-ae73-4dd2-a122-158703579828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật'])[1]/following::a[3]</value>
      <webElementGuid>d2399daf-8964-4eeb-8e22-28ab86b5c7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công Ty Cổ Phần ITFirst Pro'])[1]/preceding::a[1]</value>
      <webElementGuid>1e09bd40-17ac-4072-ac7a-cbf28931671b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test1']/parent::*</value>
      <webElementGuid>32f36f90-bfde-4a48-b860-236212834ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9CDA9.html')]</value>
      <webElementGuid>78404f42-b6d2-4c97-89bf-f8aeccdfc33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>ce501725-e1e1-4e23-b977-cb574fdbd631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9CDA9.html' and @title = 'Test1' and (text() = '
                    Test1
                                         (Mới)                                     ' or . = '
                    Test1
                                         (Mới)                                     ')]</value>
      <webElementGuid>9e6fcd45-ce60-467e-a17e-a1e88f3e49e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
