<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test1                                    _8a783d</name>
   <tag></tag>
   <elementGuidId>e544cdc7-4c85-4b0c-b95a-a451cce51fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.job_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='job-item-35B9C1B1']/div/div[2]/div/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>753f3fae-00dd-4602-acff-156d06086148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job_link</value>
      <webElementGuid>2923d949-7026-4641-b1f1-96e36812e685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>35B9C1B1</value>
      <webElementGuid>a7e754c7-aa4b-498a-b493-a332ee30f5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C1B1.html</value>
      <webElementGuid>d3d3261d-5531-43b0-8e5d-69cc00132962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>660edbb6-20e3-4e57-807d-55c7f8d96b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test1</value>
      <webElementGuid>bf35cc34-c5c5-408a-b491-4b8ed478f089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Test1
                                         (Mới)                                     </value>
      <webElementGuid>d2b5a5a0-7ad3-489d-95a3-c3093539a093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-item-35B9C1B1&quot;)/div[@class=&quot;figure&quot;]/div[@class=&quot;figcaption&quot;]/div[@class=&quot;title&quot;]/h2[1]/a[@class=&quot;job_link&quot;]</value>
      <webElementGuid>a18d83a3-5007-4f48-87b6-3efc8e9d3a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-item-35B9C1B1']/div/div[2]/div/h2/a</value>
      <webElementGuid>e029452e-6a45-4ee3-afe4-ba6acd847321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mức lương'])[2]/following::a[2]</value>
      <webElementGuid>145c38c3-b880-4b04-ad53-b4a178cd0c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật'])[1]/following::a[3]</value>
      <webElementGuid>6442c2eb-802d-4edb-a9f6-49e96c0f667f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công Ty Cổ Phần ITFirst Pro'])[1]/preceding::a[1]</value>
      <webElementGuid>a1908cad-5e82-4c8f-84b0-579c34d910a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test1']/parent::*</value>
      <webElementGuid>206b3875-30ad-457e-a5a5-69f558986f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C1B1.html')]</value>
      <webElementGuid>9e783d32-6a99-42c0-a2e8-fc3ca4a19f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>29b29146-4592-46c1-a18f-e9438dea17a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C1B1.html' and @title = 'Test1' and (text() = '
                    Test1
                                         (Mới)                                     ' or . = '
                    Test1
                                         (Mới)                                     ')]</value>
      <webElementGuid>958fb965-f9cc-4954-a4b6-f55aec84c7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
