<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test1                                    _8a783d</name>
   <tag></tag>
   <elementGuidId>a24884b1-f7ab-435f-ac5b-708f88a89248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/main/section[2]/div/div/div[1]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/div[1]/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.job_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3080e9b8-4207-4042-98e7-ba4509e48bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job_link</value>
      <webElementGuid>ab491d8f-fa88-4068-af0e-f49c43fb0c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>35B9C9BD</value>
      <webElementGuid>66ff5993-183e-42d5-a308-65c2dd7451c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C9BD.html</value>
      <webElementGuid>7864dfaa-fc61-40db-904a-6c55dc866536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bbbbf607-2680-4252-a65d-5e54a61babf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test1</value>
      <webElementGuid>8de680fd-6209-4cc1-966c-e1feceb23e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Test1
                                         (Mới)                                     </value>
      <webElementGuid>782da773-8b2c-4006-b658-818733b1912b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-item-35B9C9BD&quot;)/div[@class=&quot;figure&quot;]/div[@class=&quot;figcaption&quot;]/div[@class=&quot;title&quot;]/h2[1]/a[@class=&quot;job_link&quot;]</value>
      <webElementGuid>9b98a5fb-c8ce-428a-9a24-ae9b9a67364c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-item-35B9C9BD']/div/div[2]/div/h2/a</value>
      <webElementGuid>72b28aff-931c-4352-a888-c5d8202cd6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mức lương'])[2]/following::a[2]</value>
      <webElementGuid>b64c961d-3c6b-4fe3-9903-00028f4cb382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật'])[1]/following::a[3]</value>
      <webElementGuid>cd08eca0-4404-49c0-91b6-fc8532c6b641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công Ty Cổ Phần ITFirst Pro'])[1]/preceding::a[1]</value>
      <webElementGuid>3b7d0700-1ca7-41ee-8417-efda2e6323b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test1']/parent::*</value>
      <webElementGuid>731c0f52-df98-46f4-a050-35b4e1b31da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C9BD.html')]</value>
      <webElementGuid>1f599369-8e2c-49d2-80e7-d87fd71e610b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>a0e3f36b-a61a-4e6f-8748-3e082bc29b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://careerbuilder.vn/vi/tim-viec-lam/test1.35B9C9BD.html' and @title = 'Test1' and (text() = '
                    Test1
                                         (Mới)                                     ' or . = '
                    Test1
                                         (Mới)                                     ')]</value>
      <webElementGuid>c090fb0c-63a9-4d55-8998-9441a3f5f996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
